[versions]
kotlin = "1.7.10"
cucumber = "7.11.2"

[libraries]
cucumber-java = {module = "io.cucumber:cucumber-java",  version.ref="cucumber"}
cucumber-junit = {module = "io.cucumber:cucumber-junit",  version.ref="cucumber"}
cucumber-java8 = {module = "io.cucumber:cucumber-java8",  version.ref="cucumber"}

[bundles]
cucumber = ["cucumber-java", "cucumber-junit", "cucumber-java8"]

[plugins]
kotlin-jvm = {id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin"}